name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  Env:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: "3.10"  # Version range or exact version of a Python version to use, the same as actions/setup-python
          version: 1.4.0       # The version of PDM to install. Leave it as empty to use the latest version from PyPI
          prerelease: true     # Allow prerelease versions to be installed
          enable-pep582: true  # Enable PEP 582 package loading globally
      - name: Install dependencies
        run: |
          pip uninstall resolvelib
          cd docs
          pdm install
          make html
